In [1]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
import warnings
warnings.simplefilter("ignore")

In [2]:
import tensorflow 

In [3]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam

In [4]:
iris_data=load_iris()

In [5]:
iris_data

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [6]:
print(iris_data.data[:5])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


In [7]:
print(iris_data.target[:5])

[0 0 0 0 0]


In [8]:
X=iris_data.data

In [9]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [10]:
X.shape

(150, 4)

In [11]:
y=iris_data.target.reshape(-1,1)
y

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
    

In [12]:
encoder=OneHotEncoder(sparse=False)
y=encoder.fit_transform(y)
print(y)

[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0.

In [13]:
x_train,x_test,y_train, y_test=train_test_split(X,y,test_size=0.20,random_state=11)

In [14]:
x_train.shape

(120, 4)

# Model Building

# 1.building Architec of the model

####2. Model Prediction

####3. model Evaluate

In [15]:
model=Sequential()
#we have to arrange Sequential that so we ar e using the equential

In [16]:
model.add(Dense(10,input_shape=(4,),activation='relu'))
#Dense is used to craete  layer of a neuron
#10-Neurons no ..
#input_shape=No of  input featuers(no of input columns)
#activation==all 10 Neurons are activate in 'Relu'(transformation oparation )

Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


In [17]:
#craeting second  hiddeen Layer
model.add(Dense(10,activation='relu'))
#no need to mention the Input shape beacuse alredy we are mention on our 1st Layer ..now its taking data from the First Layer
#We can Create N no of Layers

In [18]:
#craeting output Layer
model.add(Dense(3,activation='softmax'))
#3===no of calsess we have on our Target variable
#Softmax==Activation function for the output layer 

In [19]:
optimizer=Adam(lr=0.001)
#Adam one kind of optimizer
#lr=Learning Rate(Grediant Decent)

In [20]:
#compiling the Model
model.compile(optimizer,loss='categorical_crossentropy',metrics=['accuracy'])
#Optimizer== variable taken for optimize on above cell
#loss=loss fuction there is several loss function is there ,but Here We are dealing with the Catagorical data that so we taken → categorical_crossentropy
#Metics==evaluate Matrics ,
#Why Accuracy?===hence we know this a classification problem that so we are using the Accuracy


In [21]:
#Saw the Model of our Model
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 10)                50        
_________________________________________________________________
dense_1 (Dense)              (None, 10)                110       
_________________________________________________________________
dense_2 (Dense)              (None, 3)                 33        
Total params: 193
Trainable params: 193
Non-trainable params: 0
_________________________________________________________________


# Parm# No of weights ==  (No of input shape +1)* No of Neurorns

# Model building End

In [22]:
#epochs== no of ittretion
model.fit(x_train,y_train,batch_size=5,epochs=40)

Epoch 1/40
120/120 [==============================] - 0s 3ms/sample - loss: 0.8869 - acc: 0.4000
Epoch 2/40
120/120 [==============================] - 0s 196us/sample - loss: 0.8401 - acc: 0.5000
Epoch 3/40
120/120 [==============================] - 0s 197us/sample - loss: 0.7978 - acc: 0.6667
Epoch 4/40
120/120 [==============================] - 0s 191us/sample - loss: 0.7566 - acc: 0.8417
Epoch 5/40
120/120 [==============================] - 0s 186us/sample - loss: 0.7203 - acc: 0.8250
Epoch 6/40
120/120 [==============================] - 0s 159us/sample - loss: 0.6850 - acc: 0.8250
Epoch 7/40
120/120 [==============================] - 0s 175us/sample - loss: 0.6550 - acc: 0.8083
Epoch 8/40
120/120 [==============================] - 0s 169us/sample - loss: 0.6204 - acc: 0.8417
Epoch 9/40
120/120 [==============================] - 0s 178us/sample - loss: 0.5923 - acc: 0.8250
Epoch 10/40
120/120 [==============================] - 0s 187us/sample - loss: 0.5618 - acc: 0.9333
Epoch 11/40

In [23]:
result=model.evaluate(x_test,y_test)

30/30 [==============================] - 0s 709us/sample - loss: 0.1984 - acc: 1.0000


In [24]:
#model.save('iris_first.h5')